language: c

env: HOW_DOC=doc HOW_CONFIG=how.json HOW_OUT=_doc

install:
    - wget https://ocsigen.org/how.sh
    - . how.sh
    - how-install

script:
    - how-generate
    - how-redirect "$HOW_LATEST/manual/quickstart" $HOW_OUT/index.html
    - how-redirect-manual $HOW_LATEST latest

deploy:
  provider: pages
  keep-history: true
  skip-cleanup: true
  github-token: $GHP_TOKEN
  local-dir: _doc
  on:
    branch: wikidoc
